name: Build newt

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.2'
          
      - name: Checkout mynewt-newt
        uses: actions/checkout@v2

      - name: Install mynewt
        run: |
          go install
